apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-k8s-sa
  namespace: {{ .Values.global.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: sql-proxy-sa@project-60addf72-be9c-4c26-8db.iam.gserviceaccount.com